### ISSUE TITLE
Issue with parsing some feeds

### ISSUE THREAD

**Issue by shahidmau** [alabeduarte/feedparser-promised#19] opened 2017-11-23 06:02 UTC
I am using your awesome script to get rss feed data. But it is giving error for some feeds even though feed url is correct.

http://www.businessfirstmagazine.com.au/feed/

you can check that above is a valid rss feed.
http://www.feedbucket.com/?src=http%3A%2F%2Fwww.businessfirstmagazine.com.au%2Ffeed%2F

Thanks.

**Comment by alabeduarte** [comment] 2017-12-17 00:47
Hi @shahidmau 

Sorry for the delay response, I'll have a look early this week. Same goes to https://github.com/alabeduarte/feedparser-promised/issues/20

Cheers

**Comment by alabeduarte** [comment] 2018-02-28 22:02
Hi @shahidmau 

Same as #20, I'm closing this one but let me know if you think the issue is still getting on your way.

Cheers

**Closed as completed by alabeduarte** 2018-02-28 22:02 UTC
