### ISSUE TITLE
Update the @types/request = 0.0.45

### ISSUE THREAD

**Issue by exactmultiple3425** [alabeduarte/feedparser-promised#17] opened 2017-08-14 09:10 UTC
When using typescript 2.4 to compile, compiling @types/request will result in error because of compatibility issue, it is fixed in version 0.0.45

**Comment by alabeduarte** [comment] 2017-08-21 11:54
Hi @joseph1125 

Thank you for open the issue and sorry for the late response.

Could you post here the error stacktrace or some example that I can reproduce? I'm asking to make sure the problem was fixed just by updating the package as you're suggesting. Even better, would you be happy to send a pull request with this change?

Thanks in advance!!

**Comment by exactmultiple3425** [comment] 2017-08-21 12:00
Pull request: #18

**Comment by alabeduarte** [comment] 2017-08-21 14:56
Hi @joseph1125 

I have merged the PR but seems like GitHub and Travis-CI are having [issues](https://www.traviscistatus.com/incidents/tjfn9tf5vp83) to integrate. I'll monitor it during the next hours and I'll let you know once the new package version will be published.

Thanks!

**Comment by alabeduarte** [comment] 2017-08-21 15:04
Done, the build has finished and the version `1.4.2` is out. 

Thank you!

**Closed as completed by alabeduarte** 2017-08-21 15:04 UTC
